version: v1.1.0

steps:
- cmd: |
    bash -c 'echo "FROM arm32v6/alpine:3.5
    RUN uname -a
    RUN uname -m" > dockerfile.arm32'
- cmd: |
    bash -c 'echo "FROM alpine:3.5
    RUN uname -a
    RUN uname -m" > dockerfile.amd64'
- build: -t $Registry/multi-arch:arm32 -f dockerfile.arm32 .
- build: -t $Registry/multi-arch:amd64 -f dockerfile.amd64 .
- cmd: docker push $Registry/multi-arch:amd64
- cmd: docker push $Registry/multi-arch:arm32
- cmd: >
    docker manifest create
    $Registry/multi-arch:latest
    $Registry/multi-arch:arm32
    $Registry/multi-arch:amd64
- cmd: docker manifest push --purge $Registry/multi-arch:latest
- cmd: docker manifest inspect $Registry/multi-arch:latest
